﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers.LightGbm;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace Odev
{
    public partial class MLModel1
    {
        public static ITransformer RetrainPipeline(MLContext context, IDataView trainData)
        {
            var pipeline = BuildPipeline(context);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"FTHomeGol", @"FTHomeGol"),new InputOutputColumnPair(@"FTAwayGol", @"FTAwayGol"),new InputOutputColumnPair(@"HomeShot", @"HomeShot"),new InputOutputColumnPair(@"AwayShot", @"AwayShot"),new InputOutputColumnPair(@"HomeCorner", @"HomeCorner")})      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"HomeTeam",outputColumnName:@"HomeTeam"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"AwayTeam",outputColumnName:@"AwayTeam"))      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"FTHomeGol",@"FTAwayGol",@"HomeShot",@"AwayShot",@"HomeCorner",@"HomeTeam",@"AwayTeam"}))      
                                    .Append(mlContext.Regression.Trainers.LightGbm(new LightGbmRegressionTrainer.Options(){NumberOfLeaves=4,NumberOfIterations=10,MinimumExampleCountPerLeaf=20,LearningRate=0.220732061719194,LabelColumnName=@"AwayCorner",FeatureColumnName=@"Features",ExampleWeightColumnName=null,Booster=new GradientBooster.Options(){SubsampleFraction=0.679008023512308,FeatureFraction=0.99999999,L1Regularization=2E-10,L2Regularization=0.0502835708021913},MaximumBinCountPerFeature=236}));

            return pipeline;
        }
    }
}
